[package]
name = "infotheory"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[workspace]
members = [".", "zpaq_rs", "rosa"]
resolver = "3"

[dependencies]
zpaq_rs = {path = "./zpaq_rs"}
rosaplus = {path = "./rosa"}
rwkvzip = {path = "./rwkvzip", default-features = false}
rayon = "*"
num_cpus = "*"
once_cell = "*"


[[bench]]
name = "par"
harness = false

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
panic = "abort"

[profile.bench]
inherits = "release"
lto = "fat"
codegen-units = 1
opt-level = 3
debug = true
