//! Public type definitions for the spec-first API surface.

use crate::coders::CoderType;
use std::sync::Arc;

/// How generated symbols should update the model state.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum GenerationUpdateMode {
    /// Keep adapting/fitting on generated bytes.
    Adaptive,
    /// Freeze fitted parameters/statistics and only advance conditioning state.
    Frozen,
}

/// How to pick the next byte from the model distribution.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum GenerationStrategy {
    /// Deterministic argmax over the next-byte distribution.
    Greedy,
    /// Seeded sampling from the next-byte distribution.
    Sample,
}

/// Generation options shared by the library API and CLI.
#[derive(Clone, Copy, Debug)]
pub struct GenerationConfig {
    /// Byte-selection strategy.
    pub strategy: GenerationStrategy,
    /// Whether generated bytes should keep adapting the model.
    pub update_mode: GenerationUpdateMode,
    /// RNG seed used by [`GenerationStrategy::Sample`].
    pub seed: u64,
    /// Softmax temperature for sampling. `<= 0` behaves like greedy.
    pub temperature: f64,
    /// Optional top-k truncation. `0` disables it.
    pub top_k: usize,
    /// Optional nucleus truncation. Values `>= 1.0` disable it.
    pub top_p: f64,
}

impl Default for GenerationConfig {
    fn default() -> Self {
        Self::sampled_frozen(42)
    }
}

impl GenerationConfig {
    /// Deterministic frozen continuation.
    pub const fn greedy_frozen() -> Self {
        Self {
            strategy: GenerationStrategy::Greedy,
            update_mode: GenerationUpdateMode::Frozen,
            seed: 0xD00D_F00D_CAFE_BABEu64,
            temperature: 1.0,
            top_k: 0,
            top_p: 1.0,
        }
    }

    /// Seeded frozen sampling from the model distribution.
    pub const fn sampled_frozen(seed: u64) -> Self {
        Self {
            strategy: GenerationStrategy::Sample,
            update_mode: GenerationUpdateMode::Frozen,
            seed,
            temperature: 1.0,
            top_k: 0,
            top_p: 1.0,
        }
    }
}

/// Core predictive model class used by the library.
///
/// `RateBackend` is the shared model class behind entropy-rate estimation,
/// rate-coded compression, generation, and the world-model interface used by
/// MC-AIXI/AIQI planners.
#[derive(Clone)]
pub enum RateBackend {
    /// ROSA+ suffix-automaton estimator.
    RosaPlus,
    /// Local contiguous match predictor.
    Match {
        /// Number of retained hash bits for suffix lookup.
        hash_bits: usize,
        /// Minimum repeat length required before predicting.
        min_len: usize,
        /// Maximum repeat length used for confidence scaling.
        max_len: usize,
        /// Residual probability mass left for non-match symbols.
        base_mix: f64,
        /// Confidence multiplier applied to short-match tapering.
        confidence_scale: f64,
    },
    /// Sparse/gapped local match predictor.
    SparseMatch {
        /// Number of retained hash bits for spaced-suffix lookup.
        hash_bits: usize,
        /// Minimum spaced repeat length required before predicting.
        min_len: usize,
        /// Maximum spaced repeat length used for confidence scaling.
        max_len: usize,
        /// Minimum gap between matched bytes.
        gap_min: usize,
        /// Maximum gap between matched bytes.
        gap_max: usize,
        /// Residual probability mass left for non-match symbols.
        base_mix: f64,
        /// Confidence multiplier applied to short-match tapering.
        confidence_scale: f64,
    },
    /// Pure-Rust bounded-memory PPMD-style model.
    Ppmd {
        /// Maximum context order.
        order: usize,
        /// Approximate memory budget in MiB.
        memory_mb: usize,
    },
    /// Exact online Sequitur grammar backend with byte-level predictive readout.
    Sequitur {
        /// Maximum number of terminal bytes retained per grammar-derived context.
        context_bytes: usize,
    },
    #[cfg(feature = "backend-mamba")]
    /// Mamba method string (e.g. `file:...` or `cfg:...[;policy:...]`) resolved lazily.
    MambaMethod {
        /// Mamba method string.
        method: String,
    },
    #[cfg(feature = "backend-rwkv")]
    /// RWKV7 method string (e.g. `file:...` or `cfg:...[;policy:...]`) resolved lazily.
    Rwkv7Method {
        /// RWKV7 method string.
        method: String,
    },
    /// ZPAQ compression-based rate model (streamable methods only).
    Zpaq {
        /// ZPAQ method string (streamable modes only for rate estimation).
        method: String,
    },
    /// Online mixture over `RateBackend` experts.
    ///
    /// `Bayes`, `Switching`, and `Convex` follow
    /// "On Ensemble Techniques for AIXI Approximation"; `FadingBayes`,
    /// `Mdl`, and `Neural` are repository extensions.
    Mixture {
        /// Mixture expert/runtime specification.
        spec: Arc<MixtureSpec>,
    },
    /// Particle-latent filter ensemble.
    Particle {
        /// Particle filter specification.
        spec: Arc<ParticleSpec>,
    },
    /// Calibrated wrapper over another bytewise backend.
    Calibrated {
        /// Calibration specification.
        spec: Arc<CalibratedSpec>,
    },
    /// Action-Conditional CTW (single context tree).
    Ctw {
        /// Context tree depth.
        depth: usize,
    },
    /// Factorized Action-Conditional CTW (k trees for k-bit percepts).
    FacCtw {
        /// Base context depth.
        base_depth: usize,
        /// Number of percept bits.
        num_percept_bits: usize,
        /// Encoding width in bits.
        encoding_bits: usize,
    },
}

/// Compression backend used by NCD/compression-size operations.
#[derive(Clone)]
pub enum CompressionBackend {
    /// ZPAQ compressor with explicit method string.
    Zpaq {
        /// ZPAQ method (for example `"1"` or `"5"`).
        method: String,
    },
    #[cfg(feature = "backend-rwkv")]
    /// RWKV7 compressor configured by canonical method string.
    Rwkv7 {
        /// RWKV7 method string (for example `file:...` or `cfg:...[;policy:...]`).
        method: String,
        /// Entropy coder used for coding model PDFs.
        coder: CoderType,
    },
    /// Generic rate-coded compressor wrapping an arbitrary rate backend.
    Rate {
        /// Predictive rate backend.
        rate_backend: RateBackend,
        /// Entropy coder used for coding model PDFs.
        coder: CoderType,
        /// Framing mode for output payloads.
        framing: crate::compression::FramingMode,
    },
}

/// Shared maximum nesting depth for recursive mixture specifications.
pub const MAX_MIXTURE_NESTING: usize = 8;

/// Mixture policy kind for rate-backend mixtures.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum MixtureKind {
    /// Standard Bayesian mixture with fixed expert weights.
    Bayes,
    /// Bayesian mixture with exponential weight decay.
    FadingBayes,
    /// Switching mixture using the fixed-share update from
    /// "On Ensemble Techniques for AIXI Approximation".
    Switching,
    /// Online convex mixture with projected-simplex weight updates.
    Convex,
    /// MDL-style best-expert selector.
    Mdl,
    /// Bytewise neural logistic mixer (fx2-cmix style adaptation).
    Neural,
}

/// Adaptive schedule family for switching and convex mixtures.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum MixtureScheduleMode {
    /// Use the implementation's default exposed parameterization.
    ///
    /// - `Switching`: constant switch rate `alpha`
    /// - `Convex`: step size `alpha / sqrt(t)`
    Default,
    /// Use the theorem schedule from
    /// "On Ensemble Techniques for AIXI Approximation".
    ///
    /// - `Switching`: `alpha_t = 1 / t`
    /// - `Convex`: `eta_t = epsilon / sqrt(t)` under this implementation's
    ///   natural-log gradient, matching the bit-loss schedule analyzed in
    ///   "On Ensemble Techniques for AIXI Approximation" after
    ///   accounting for the `1 / ln(2)` factor in the base-2 gradient
    ///
    /// This preserves configured expert priors; exact theorem hypotheses for
    /// switching still additionally require uniform priors.
    Theorem,
}

impl Default for MixtureScheduleMode {
    fn default() -> Self {
        Self::Default
    }
}

/// Fixed context families for calibrated PDF wrappers.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CalibrationContextKind {
    /// Single global calibration row.
    Global,
    /// Previous-byte class only.
    ByteClass,
    /// Text-structure-aware context hash.
    Text,
    /// Repeat-aware context hash.
    Repeat,
    /// Joint text/repeat-aware context hash.
    TextRepeat,
}

/// Configuration for a calibrated wrapper rate backend.
#[derive(Clone)]
pub struct CalibratedSpec {
    /// Base backend whose PDF is calibrated.
    pub base: RateBackend,
    /// Context family controlling table row selection.
    pub context: CalibrationContextKind,
    /// Number of probability bins per row.
    pub bins: usize,
    /// Online learning rate for observed-symbol updates.
    pub learning_rate: f64,
    /// Symmetric clip applied to calibration weights.
    pub bias_clip: f64,
}

/// Expert specification for mixture backends.
#[derive(Clone)]
pub struct MixtureExpertSpec {
    /// Optional expert display name.
    pub name: Option<String>,
    /// Log prior weight (natural log). Uniform priors can be `0.0`.
    pub log_prior: f64,
    /// Max order for ROSA experts (ignored for other backends).
    pub max_order: i64,
    /// Underlying backend for this expert.
    pub backend: RateBackend,
}

/// Mixture specification for rate-backend mixtures.
#[derive(Clone)]
pub struct MixtureSpec {
    /// Mixture policy.
    pub kind: MixtureKind,
    /// Adaptive schedule family for supported mixture kinds.
    pub schedule: MixtureScheduleMode,
    /// Shared scalar parameter: switch rate for `Switching`, step-size scale for `Convex`,
    /// learning rate for `Neural`, and generic alpha for the remaining families.
    ///
    /// In theorem mode for `Switching` and `Convex`, this field is retained for API
    /// compatibility but is not used by the update schedule.
    pub alpha: f64,
    /// Decay factor for fading Bayes mixtures.
    pub decay: Option<f64>,
    /// Expert list.
    pub experts: Vec<MixtureExpertSpec>,
}

/// Configuration for a particle-latent filter ensemble rate backend.
#[derive(Clone, Debug)]
pub struct ParticleSpec {
    /// Number of particles in the ensemble.
    pub num_particles: usize,
    /// Context window length for rolling byte context.
    pub context_window: usize,
    /// Number of latent update unroll steps per byte.
    pub unroll_steps: usize,
    /// Number of latent cells per particle.
    pub num_cells: usize,
    /// Dimensionality of each latent cell.
    pub cell_dim: usize,
    /// Number of discrete rules for soft routing.
    pub num_rules: usize,
    /// Hidden dimension for the selector MLP.
    pub selector_hidden: usize,
    /// Hidden dimension for each rule MLP.
    pub rule_hidden: usize,
    /// Dimension of per-rule noise input (ignored when deterministic).
    pub noise_dim: usize,
    /// Whether to use fully deterministic execution (no RNG).
    pub deterministic: bool,
    /// Whether to inject noise into rule inputs (ignored when deterministic).
    pub enable_noise: bool,
    /// Base scale for deterministic hash-noise injected into rule inputs.
    pub noise_scale: f64,
    /// Number of steps over which injected noise linearly anneals to zero.
    pub noise_anneal_steps: usize,
    /// Learning rate for readout layer SGD.
    pub learning_rate_readout: f64,
    /// Learning rate for selector MLP SGD.
    pub learning_rate_selector: f64,
    /// Learning rate for rule MLP SGD.
    pub learning_rate_rule: f64,
    /// Truncated backpropagation-through-time depth (number of recent steps).
    pub bptt_depth: usize,
    /// Momentum coefficient for selector/rule online updates (in [0, 1)).
    pub optimizer_momentum: f64,
    /// Gradient clipping threshold (max abs value per element).
    pub grad_clip: f64,
    /// Latent cell state clipping threshold (max abs value per element).
    pub state_clip: f64,
    /// Forgetting factor for particle log-weights (0 = no forgetting).
    pub forget_lambda: f64,
    /// Effective sample size ratio threshold for resampling (in (0, 1]).
    pub resample_threshold: f64,
    /// Fraction of particles to mutate after resampling (in [0, 1]).
    pub mutate_fraction: f64,
    /// Scale of hash-noise perturbation applied during mutation.
    pub mutate_scale: f64,
    /// Whether mutation also perturbs model parameters (state is always mutated).
    pub mutate_model_params: bool,
    /// Diagnostics print interval in steps (0 disables particle diagnostics logs).
    pub diagnostics_interval: usize,
    /// Minimum probability floor for numerical stability.
    pub min_prob: f64,
    /// Master seed for deterministic initialization and mutation.
    pub seed: u64,
}

#[allow(clippy::derivable_impls)]
impl Default for RateBackend {
    fn default() -> Self {
        #[cfg(feature = "backend-rosa")]
        {
            RateBackend::RosaPlus
        }
        #[cfg(all(not(feature = "backend-rosa"), feature = "backend-zpaq"))]
        {
            RateBackend::Zpaq {
                method: "1".to_string(),
            }
        }
        #[cfg(all(not(feature = "backend-rosa"), not(feature = "backend-zpaq")))]
        {
            RateBackend::Ctw { depth: 16 }
        }
    }
}

impl RateBackend {
    /// Serialize this backend into deterministic canonical JSON.
    pub fn to_canonical_json(&self) -> crate::spec::SpecResult<String> {
        crate::spec::rate_backend_to_canonical_json(self)
    }

    /// Serialize this backend into canonical JSON value form.
    pub fn to_canonical_json_value(&self) -> crate::spec::SpecResult<serde_json::Value> {
        crate::spec::rate_backend_to_json_value(self)
    }
}

#[cfg(feature = "backend-zpaq")]
impl Default for CompressionBackend {
    fn default() -> Self {
        CompressionBackend::Zpaq {
            method: "5".to_string(),
        }
    }
}

#[cfg(not(feature = "backend-zpaq"))]
impl Default for CompressionBackend {
    fn default() -> Self {
        CompressionBackend::Rate {
            rate_backend: RateBackend::default(),
            coder: crate::coders::CoderType::AC,
            framing: crate::compression::FramingMode::Raw,
        }
    }
}

impl CompressionBackend {
    /// Serialize this backend into deterministic canonical JSON.
    pub fn to_canonical_json(&self) -> crate::spec::SpecResult<String> {
        crate::spec::compression_backend_to_canonical_json(self)
    }

    /// Serialize this backend into canonical JSON value form.
    pub fn to_canonical_json_value(&self) -> crate::spec::SpecResult<serde_json::Value> {
        crate::spec::compression_backend_to_json_value(self)
    }
}

use crate::error::{InfotheoryError, InfotheoryResult};

/// Parse a mixture kind name with the shared alias table used across CLI, Python, and WASM.
pub fn parse_mixture_kind_name(kind: &str) -> Result<MixtureKind, String> {
    match kind.trim().to_ascii_lowercase().as_str() {
        "bayes" | "bayes-mix" | "bayes_mix" => Ok(MixtureKind::Bayes),
        "fading" | "fading-bayes" | "fading_bayes" => Ok(MixtureKind::FadingBayes),
        "switch" | "switching" | "switch-mix" | "switch_mix" => Ok(MixtureKind::Switching),
        "convex" | "convex-mix" | "convex_mix" => Ok(MixtureKind::Convex),
        "mdl" | "selector" | "mdr" => Ok(MixtureKind::Mdl),
        "neural" | "neural-mix" | "neural_mix" | "mix" | "mixture" | "fx2" | "fx2-cmix"
        | "fx2_cmix" => Ok(MixtureKind::Neural),
        other => Err(format!("unknown mixture kind '{other}'")),
    }
}

/// Parse a mixture schedule mode with the shared alias table used across CLI, Python, and WASM.
pub fn parse_mixture_schedule_name(schedule: &str) -> Result<MixtureScheduleMode, String> {
    match schedule.trim().to_ascii_lowercase().as_str() {
        "" | "default" | "constant" | "const" => Ok(MixtureScheduleMode::Default),
        "theorem" | "paper" | "paper-theorem" | "paper_theorem" => Ok(MixtureScheduleMode::Theorem),
        other => Err(format!("unknown mixture schedule '{other}'")),
    }
}

impl MixtureSpec {
    /// Build a mixture specification from kind and expert list.
    pub fn new(kind: MixtureKind, experts: Vec<MixtureExpertSpec>) -> Self {
        Self {
            kind,
            schedule: MixtureScheduleMode::Default,
            alpha: 0.01,
            decay: None,
            experts,
        }
    }

    /// Set the schedule family.
    pub fn with_schedule(mut self, schedule: MixtureScheduleMode) -> Self {
        self.schedule = schedule;
        self
    }

    /// Set the family-specific alpha parameter.
    pub fn with_alpha(mut self, alpha: f64) -> Self {
        self.alpha = alpha;
        self
    }

    /// Set fading decay factor.
    pub fn with_decay(mut self, decay: f64) -> Self {
        self.decay = Some(decay);
        self
    }

    /// Validate the mixture configuration before building runtime state.
    pub fn validate(&self) -> InfotheoryResult<()> {
        validate_mixture_spec_with_depth(self, MAX_MIXTURE_NESTING)
            .map_err(InfotheoryError::invalid_backend_config)
    }

    /// Convert to executable expert configs for runtime mixture evaluation.
    pub fn build_experts(&self) -> Vec<crate::mixture::ExpertConfig> {
        self.experts
            .iter()
            .map(|spec| {
                crate::mixture::ExpertConfig::from_rate_backend(
                    spec.name.clone(),
                    spec.log_prior,
                    spec.backend.clone(),
                    spec.max_order,
                )
            })
            .collect()
    }

    /// Serialize this spec into deterministic canonical JSON.
    pub fn to_canonical_json(&self) -> crate::spec::SpecResult<String> {
        serde_json::to_string_pretty(&crate::spec::mixture_spec_to_json_value(self)?)
            .map_err(crate::spec::SpecError::from)
    }

    /// Serialize this spec into canonical JSON value form.
    pub fn to_canonical_json_value(&self) -> crate::spec::SpecResult<serde_json::Value> {
        crate::spec::mixture_spec_to_json_value(self)
    }
}

fn validate_mixture_spec_with_depth(spec: &MixtureSpec, depth: usize) -> Result<(), String> {
    if depth == 0 {
        return Err("mixture spec nesting too deep".to_string());
    }
    validate_mixture_spec_shallow(spec)?;
    for (index, expert) in spec.experts.iter().enumerate() {
        validate_rate_backend_with_depth(&expert.backend, depth - 1).map_err(|err| {
            if let Some(name) = expert.name.as_deref() {
                format!("mixture expert '{name}' invalid: {err}")
            } else {
                format!("mixture expert #{} invalid: {err}", index + 1)
            }
        })?;
    }
    Ok(())
}

fn validate_mixture_spec_shallow(spec: &MixtureSpec) -> Result<(), String> {
    if spec.experts.is_empty() {
        return Err("mixture spec must include at least one expert".to_string());
    }
    if !spec.alpha.is_finite() {
        return Err("mixture alpha must be finite".to_string());
    }
    if spec
        .experts
        .iter()
        .any(|expert| !expert.log_prior.is_finite())
    {
        return Err("mixture expert log_prior must be finite".to_string());
    }
    if let Some(decay) = spec.decay {
        if !decay.is_finite() || !(0.0..1.0).contains(&decay) {
            return Err("mixture decay must be in (0, 1)".to_string());
        }
    }
    if matches!(spec.kind, MixtureKind::FadingBayes) && spec.decay.is_none() {
        return Err("fading Bayes mixture requires decay".to_string());
    }
    if spec.schedule != MixtureScheduleMode::Default
        && !matches!(spec.kind, MixtureKind::Switching | MixtureKind::Convex)
    {
        return Err(
            "mixture schedule is only supported for switching and convex mixtures".to_string(),
        );
    }
    match (spec.kind, spec.schedule) {
        (MixtureKind::Switching, MixtureScheduleMode::Default) => {
            if !(0.0..=1.0).contains(&spec.alpha) {
                return Err("switching mixture alpha must be in [0, 1]".to_string());
            }
        }
        (MixtureKind::Convex, MixtureScheduleMode::Default)
        | (MixtureKind::Neural, MixtureScheduleMode::Default) => {
            if spec.alpha <= 0.0 {
                return Err("mixture alpha must be > 0".to_string());
            }
        }
        (MixtureKind::Neural, MixtureScheduleMode::Theorem) => unreachable!(),
        _ => {}
    }
    Ok(())
}

fn validate_rate_backend_with_depth(backend: &RateBackend, depth: usize) -> Result<(), String> {
    let descriptor = crate::runtime::describe_rate_backend(backend);
    if !descriptor.enabled {
        let feature = descriptor
            .feature
            .expect("disabled backend descriptors must declare a required feature");
        return Err(format!(
            "backend '{}' requires infotheory feature '{}'",
            descriptor.canonical, feature
        ));
    }
    match backend {
        RateBackend::Sequitur { context_bytes } => {
            if *context_bytes < 2 {
                Err("sequitur context_bytes must be >= 2".to_string())
            } else {
                Ok(())
            }
        }
        RateBackend::Mixture { spec } => validate_mixture_spec_with_depth(spec.as_ref(), depth),
        RateBackend::Particle { spec } => spec.validate().map_err(|err| err.to_string()),
        RateBackend::Calibrated { spec } => {
            if depth == 0 {
                return Err("calibrated spec nesting too deep".to_string());
            }
            validate_rate_backend_with_depth(&spec.base, depth - 1)
                .map_err(|err| format!("calibrated base invalid: {err}"))
        }
        _ => Ok(()),
    }
}

/// Validate a rate backend, including nested mixture/calibrated subgraphs.
pub fn validate_rate_backend(backend: &RateBackend) -> InfotheoryResult<()> {
    validate_rate_backend_with_depth(backend, MAX_MIXTURE_NESTING)
        .map_err(InfotheoryError::invalid_backend_config)
}

/// Validate a compression backend, including nested rate-backed compressors.
pub fn validate_compression_backend(backend: &CompressionBackend) -> InfotheoryResult<()> {
    let descriptor = crate::runtime::describe_compression_backend(backend);
    if !descriptor.enabled {
        let feature = descriptor
            .feature
            .expect("disabled backend descriptors must declare a required feature");
        return Err(InfotheoryError::invalid_backend_config(format!(
            "compression backend '{}' requires infotheory feature '{}'",
            descriptor.canonical, feature
        )));
    }
    if let CompressionBackend::Rate { rate_backend, .. } = backend {
        validate_rate_backend(rate_backend).map_err(|err| {
            InfotheoryError::invalid_backend_config(format!(
                "rate-coded compression backend invalid: {err}"
            ))
        })?;
    }
    Ok(())
}

impl Default for ParticleSpec {
    fn default() -> Self {
        Self {
            num_particles: 16,
            context_window: 32,
            unroll_steps: 2,
            num_cells: 8,
            cell_dim: 32,
            num_rules: 4,
            selector_hidden: 64,
            rule_hidden: 64,
            noise_dim: 8,
            deterministic: true,
            enable_noise: false,
            noise_scale: 0.10,
            noise_anneal_steps: 8192,
            learning_rate_readout: 0.01,
            learning_rate_selector: 1e-4,
            learning_rate_rule: 3e-4,
            bptt_depth: 3,
            optimizer_momentum: 0.05,
            grad_clip: 1.0,
            state_clip: 8.0,
            forget_lambda: 0.0,
            resample_threshold: 0.5,
            mutate_fraction: 0.1,
            mutate_scale: 0.01,
            mutate_model_params: false,
            diagnostics_interval: 0,
            min_prob: 2f64.powi(-24),
            seed: 42,
        }
    }
}

impl ParticleSpec {
    /// Validate all fields, returning an error message on failure.
    pub fn validate(&self) -> InfotheoryResult<()> {
        if self.num_particles == 0 {
            return Err(InfotheoryError::invalid_backend_config(
                "num_particles must be > 0",
            ));
        }
        if self.context_window == 0 {
            return Err(InfotheoryError::invalid_backend_config(
                "context_window must be > 0",
            ));
        }
        if self.unroll_steps == 0 {
            return Err(InfotheoryError::invalid_backend_config(
                "unroll_steps must be > 0",
            ));
        }
        if self.num_cells == 0 {
            return Err(InfotheoryError::invalid_backend_config(
                "num_cells must be > 0",
            ));
        }
        if self.cell_dim == 0 {
            return Err(InfotheoryError::invalid_backend_config(
                "cell_dim must be > 0",
            ));
        }
        if self.num_rules == 0 {
            return Err(InfotheoryError::invalid_backend_config(
                "num_rules must be > 0",
            ));
        }
        if self.selector_hidden == 0 {
            return Err(InfotheoryError::invalid_backend_config(
                "selector_hidden must be > 0",
            ));
        }
        if self.rule_hidden == 0 {
            return Err(InfotheoryError::invalid_backend_config(
                "rule_hidden must be > 0",
            ));
        }
        if !self.learning_rate_readout.is_finite() || self.learning_rate_readout < 0.0 {
            return Err(InfotheoryError::invalid_backend_config(
                "learning_rate_readout must be finite and non-negative",
            ));
        }
        if !self.learning_rate_selector.is_finite() || self.learning_rate_selector < 0.0 {
            return Err(InfotheoryError::invalid_backend_config(
                "learning_rate_selector must be finite and non-negative",
            ));
        }
        if !self.learning_rate_rule.is_finite() || self.learning_rate_rule < 0.0 {
            return Err(InfotheoryError::invalid_backend_config(
                "learning_rate_rule must be finite and non-negative",
            ));
        }
        if !self.noise_scale.is_finite() || self.noise_scale < 0.0 {
            return Err(InfotheoryError::invalid_backend_config(
                "noise_scale must be finite and non-negative",
            ));
        }
        if !self.optimizer_momentum.is_finite()
            || self.optimizer_momentum < 0.0
            || self.optimizer_momentum >= 1.0
        {
            return Err(InfotheoryError::invalid_backend_config(
                "optimizer_momentum must be finite and in [0, 1)",
            ));
        }
        if self.bptt_depth == 0 {
            return Err(InfotheoryError::invalid_backend_config(
                "bptt_depth must be > 0",
            ));
        }
        if !(self.resample_threshold > 0.0 && self.resample_threshold <= 1.0) {
            return Err(InfotheoryError::invalid_backend_config(
                "resample_threshold must be in (0, 1]",
            ));
        }
        if !(self.mutate_fraction >= 0.0 && self.mutate_fraction <= 1.0) {
            return Err(InfotheoryError::invalid_backend_config(
                "mutate_fraction must be in [0, 1]",
            ));
        }
        if !(self.min_prob > 0.0 && self.min_prob < 0.5) {
            return Err(InfotheoryError::invalid_backend_config(
                "min_prob must be in (0, 0.5)",
            ));
        }
        Ok(())
    }

    /// Serialize this spec into deterministic canonical JSON.
    pub fn to_canonical_json(&self) -> crate::spec::SpecResult<String> {
        serde_json::to_string_pretty(&crate::spec::particle_spec_to_json_value(self))
            .map_err(crate::spec::SpecError::from)
    }

    /// Serialize this spec into canonical JSON value form.
    pub fn to_canonical_json_value(&self) -> serde_json::Value {
        crate::spec::particle_spec_to_json_value(self)
    }
}

impl CalibratedSpec {
    /// Serialize this spec into deterministic canonical JSON.
    pub fn to_canonical_json(&self) -> crate::spec::SpecResult<String> {
        serde_json::to_string_pretty(&crate::spec::calibrated_spec_to_json_value(self)?)
            .map_err(crate::spec::SpecError::from)
    }

    /// Serialize this spec into canonical JSON value form.
    pub fn to_canonical_json_value(&self) -> crate::spec::SpecResult<serde_json::Value> {
        crate::spec::calibrated_spec_to_json_value(self)
    }
}
